name: Scheduled Google Sheet Analysis

on:
  schedule:
    - cron: '0 12 * * *'  # Every day at 12:00 PM UTC
  workflow_dispatch:       # Allows manual triggering in GitHub

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run analysis script
        run: python analyze.py
